name: 'HTTP Request Action'
description: 'Create any HTTP Request'
inputs:
    url:
        description: 'Request URL'
        required: true
    method:
        description: 'Request Method'
        required: false
        default: 'POST'
    contentType:
        description: 'Content Type'
        required: false
        default: 'application/json'
    data:
        description: 'Request Body as JSON String'
        required: false
        default: '{}'
outputs:
    response:
        description: 'HTTP Response Content'
runs:
    using: 'node12'
    main: 'index.js'